plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.4.5
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - db/**/*
    - bin/*
    - tmp/**/*
    - vendor/**/*
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
