name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  # --- Ruby Security Scan ---
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for Rails security vulnerabilities
        run: bin/brakeman --no-pager

  # --- Code Linting: Ruby ---
  lint_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint Ruby code with RuboCop
        run: bin/rubocop -f github

  # --- Code Linting: ERB ---
  lint_erb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install gems
        run: bundle install --jobs 4 --retry 3

      - name: Lint ERB views
        run: bundle exec erblint app/views

  # --- JavaScript Security Scan ---
  scan_js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.3.0

      - name: Install Node dependencies
        run: npm ci

      - name: Scan JS dependencies for vulnerabilities
        run: npm audit --audit-level=moderate

  # --- Code Linting: JS (ESLint + Prettier) ---
  lint_js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.3.0

      - name: Install Node dependencies
        run: npm install

      - name: Run JS Linter
        run: npm run lint

  # --- Tests ---
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:17.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: rails_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.3.0

      - name: Install Node dependencies
        run: npm ci

      - name: Build JS assets
        run: npm run build

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libjemalloc2 libvips postgresql-client

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Prepare test database
        run: bin/rails db:test:prepare
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:password@localhost:5432/rails_test

      - name: Run RSpec tests with SimpleCov
        run: bundle exec rspec
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:password@localhost:5432/rails_test

      - name: Print test coverage
        if: always()
        run: |
          if [ -f coverage/.last_run.json ]; then
            COVERAGE=$(ruby -r json -e "puts JSON.parse(File.read('coverage/.last_run.json'))['result']['covered_percent']")
            echo "Total test coverage: ${COVERAGE}%"
          else
            echo "Coverage file not found!"
          fi

      - name: Upload SimpleCov coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: Upload screenshots for failed system tests
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: tmp/screenshots
          if-no-files-found: ignore
